competitions = [
    {'name' : 'Serie A', 'league_id' : 'IT1', 'league_path' : '/serie-a', 'season' : '2021'},
    {'name' : 'Serie A', 'league_id' : 'IT1', 'league_path' : '/serie-a', 'season' : '2020'},
    {'name' : 'Serie B', 'league_id' : 'IT2', 'league_path' : '/serie-b', 'season' : '2021'},
    {'name' : 'Serie B', 'league_id' : 'IT2', 'league_path' : '/serie-b', 'season' : '2020'},
    {'name' : 'Serie c - Girone A', 'league_id' : 'IT3A', 'league_path' : '/serie-c-girone-a', 'season' : '2021'},
    {'name' : 'Serie c - Girone A', 'league_id' : 'IT3A', 'league_path' : '/serie-c-girone-a', 'season' : '2020'},
    {'name' : 'Serie c - Girone B', 'league_id' : 'IT3B', 'league_path' : '/serie-c-girone-b', 'season' : '2021'},
    {'name' : 'Serie c - Girone B', 'league_id' : 'IT3B', 'league_path' : '/serie-c-girone-b', 'season' : '2020'},
    {'name' : 'Serie c - Girone C', 'league_id' : 'IT3C', 'league_path' : '/serie-c-girone-c', 'season' : '2021'},
    {'name' : 'Serie c - Girone C', 'league_id' : 'IT3C', 'league_path' : '/serie-c-girone-c', 'season' : '2020'},
    {'name' : 'La Liga', 'league_id' : 'ES1', 'league_path' : '/laliga', 'season' : '2021'},
    {'name' : 'La Liga', 'league_id' : 'ES1', 'league_path' : '/laliga', 'season' : '2020'},
    {'name' : 'La Liga 2', 'league_id' : 'ES2', 'league_path' : '/laliga2', 'season' : '2021'},
    {'name' : 'La Liga 2', 'league_id' : 'ES2', 'league_path' : '/laliga2', 'season' : '2020'},
    {'name' : 'Ligue 1', 'league_id' : 'FR1', 'league_path' : '/ligue-1', 'season' : '2021'},
    {'name' : 'Ligue 1', 'league_id' : 'FR1', 'league_path' : '/ligue-1', 'season' : '2020'},
    {'name' : 'Ligue 2', 'league_id' : 'FR2', 'league_path' : '/ligue-2', 'season' : '2021'},
    {'name' : 'Ligue 2', 'league_id' : 'FR2', 'league_path' : '/ligue-2', 'season' : '2020'},
    {'name' : 'Championnat National', 'league_id' : 'FR3', 'league_path' : '/championnat-national', 'season' : '2021'},
    {'name' : 'Championnat National', 'league_id' : 'FR3', 'league_path' : '/championnat-national', 'season' : '2020'},
    {'name' : 'Bundesliga', 'league_id' : 'L1', 'league_path' : '/bundesliga', 'season' : '2021'},
    {'name' : 'Bundesliga', 'league_id' : 'L1', 'league_path' : '/bundesliga', 'season' : '2020'},
    {'name' : '2. Bundesliga', 'league_id' : 'L2', 'league_path' : '/2-bundesliga', 'season' : '2021'},
    {'name' : '2. Bundesliga', 'league_id' : 'L2', 'league_path' : '/2-bundesliga', 'season' : '2020'},
    {'name' : '3. Liga', 'league_id' : 'L3', 'league_path' : '/3-liga', 'season' : '2021'},
    {'name' : '3. Liga', 'league_id' : 'L3', 'league_path' : '/3-liga', 'season' : '2020'},
    {'name' : 'Premier League', 'league_id' : 'GB1', 'league_path' : '/premier-league', 'season' : '2021'},
    {'name' : 'Premier League', 'league_id' : 'GB1', 'league_path' : '/premier-league', 'season' : '2020'},
    {'name' : 'Championship', 'league_id' : 'GB2', 'league_path' : '/championship', 'season' : '2021'},
    {'name' : 'Championship', 'league_id' : 'GB2', 'league_path' : '/championship', 'season' : '2020'},
    {'name' : 'League One', 'league_id' : 'GB3', 'league_path' : '/league-one', 'season' : '2021'},
    {'name' : 'League One', 'league_id' : 'GB3', 'league_path' : '/league-one', 'season' : '2020'},
    {'name' : 'League Two', 'league_id' : 'GB4', 'league_path' : '/league-two', 'season' : '2021'},
    {'name' : 'League Two', 'league_id' : 'GB4', 'league_path' : '/league-two', 'season' : '2020'},
    {'name' : 'National League', 'league_id' : 'CNAT', 'league_path' : '/national-league', 'season' : '2021'},
    {'name' : 'National League', 'league_id' : 'CNAT', 'league_path' : '/national-league', 'season' : '2020'}
]
# NOTE: cities of the teams also include the postal code, cannot discern the two
# NOTE: cities for some teams of minor leagues may not be available